/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CheckpointRestore */

#ifndef _Included_CheckpointRestore
#define _Included_CheckpointRestore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CheckpointRestore
 * Method:    CheckTheWorldNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CheckpointRestore_CheckTheWorldNative
  (JNIEnv *, jobject);

/*
 * Class:     CheckpointRestore
 * Method:    SaveTheWorldNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_CheckpointRestore_SaveTheWorldNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     CheckpointRestore
 * Method:    RestoreTheWorldNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_CheckpointRestore_RestoreTheWorldNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     CheckpointRestore
 * Method:    MigrateTheWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CheckpointRestore_MigrateTheWorld
  (JNIEnv *, jclass);

/*
 * Class:     CheckpointRestore
 * Method:    SaveTheWorldIncremental
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CheckpointRestore_SaveTheWorldIncremental
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
